name: ci

on:
  push:
    tags:
    - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/scoop-searchr.exe
